### ISSUE TITLE
Incorrect subscriptions

### ISSUE THREAD

**Issue by thedevop** [mochi-co/mqtt#242] opened 2023-06-14 20:58 UTC
As pointed out by @x20080406 in #239, currently when a client subscribe to a/b, it will receive messages for a/b/c, a/b/c/d, etc...

Building on #239 PR, @mochi-co and @x20080406 , can you review this [commit](https://github.com/thedevop/mqtt/commit/60a32e8cce8ff894ec524adba6b981cf329a619c). I haven't dived into SharedSubscription, so please ensure it is doing that part correctly.

**Comment by mochi-co** [comment] 2023-06-14 22:32
I'm surprised this was missed for so long. I have reproduced this myself too, I am currently looking into it to see if we are solving it in the right way

**Comment by mochi-co** [comment] 2023-06-14 22:56
@thedevop I've assessed this and came to the same conclusion as you. The commit you linked resolves the issue in the most readable way, so please go ahead and PR it and I'll merge and release.

Also please add the following test to topics_test.go under TestScanSubscribers:

```go
func TestScanSubscribersTopicInheritanceBug(t *testing.T) {
	index := NewTopicsIndex()
	index.Subscribe("cl1", packets.Subscription{Qos: 0, Filter: "a/b/c"})
	index.Subscribe("cl2", packets.Subscription{Qos: 0, Filter: "a/b"})

	subs := index.scanSubscribers("a/b/c", 0, nil, new(Subscribers))
	require.Equal(t, 1, len(subs.Subscriptions))
}
```

**Comment by x20080406** [comment] 2023-06-15 02:53
> As pointed out by @x20080406 in #239, currently when a client subscribe to a/b, it will receive messages for a/b/c, a/b/c/d, etc...
> 
> Building on #239 PR, @mochi-co and @x20080406 , can you review this [commit](https://github.com/thedevop/mqtt/commit/60a32e8cce8ff894ec524adba6b981cf329a619c). I haven't dived into SharedSubscription, so please ensure it is doing that part correctly.

this commit has a  issue. it not work well on share subscribe. for example client side subscribe topic '$share/g1/a/+/b/#'. it couldn't receive message from 'a/b/b/b/b/a/c/s/d/a/d/d/f/a/sdf'

**Comment by thedevop** [comment] 2023-06-15 05:37
@x20080406 , I don't think that's a valid shared subscription. Only `$share/{ShareName}/{filter}` is allowed, so can't have multiple wildcards. Note I haven't fully read SharedSubscription spec and code, so @mochi-co would be better to comment on this.

**Comment by mochi-co** [comment] 2023-06-15 06:21
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Shared_Subscriptions is the spec for Shared Subscriptions. 

Previously I had interpreted this to mean that shared subscriptions may not end on # wildcards, but upon reading it again, I do believe @x20080406 is correct and that # is a valid component of Shared Subscriptions. 

It's technically a separate issue as the cause is unrelated to the a/b problem. It will need to be fixed in this or another PR however.

I don't have the code with me right now but from memory I should think it can be fixed by adding gatherSharedSubscriptions to the new wildcard logical block @thedevop added at the end of the scanSubscribers method.

**Comment by thedevop** [comment] 2023-06-15 06:40
I'll add gatherSharedSubscriptions in the wild if section. I didn't add at the end, as ShareName should be at least one character, after the root, it would be captured in the wild if section.

```go
	key, hasNext := isolateParticle(topic, d)
	for _, partKey := range []string{key, "+"} {
		if particle := n.particles.get(partKey); particle != nil { // [MQTT-3.3.2-3]
			if wild := particle.particles.get("#"); wild != nil && partKey != "+" {
				x.gatherSubscriptions(topic, wild, subs) // also match any subs where filter/# is filter as per 4.7.1.2
				x.gatherSharedSubscriptions(particle, subs)
			}

			if hasNext {
				x.scanSubscribers(topic, d+1, particle, subs)
			} else {
				x.gatherSubscriptions(topic, particle, subs)
				x.gatherSharedSubscriptions(particle, subs)
			}
		}
	}

	if particle := n.particles.get("#"); particle != nil {
		x.gatherSubscriptions(topic, particle, subs)
	}
```

**Comment by x20080406** [comment] 2023-06-15 08:56
I have found an new issue.  steps bellow:
1. client1 subscribe $share/g1/a/b/c1
2. client2 publish a message to a/b/c1. client1 receive the message. it's ok!
3. client1 unsubscribe $share/g1/a/b/c1
4. client1 subscribe $share/g1/a/b/c2
5. client2 publish another message to a/b/c1, client receive the message it's wrong.

there is the debug log.

> 4:54PM DBG CONNECT <<  hook=debug m={"clean":true,"id":"mqttx_5f9b7c1c","keepalive":60,"username":"iotx","version":5}
4:54PM DBG CONNACK >> mqttx_5f9b7c1c hook=debug m={"id":0,"reason":0}
4:54PM DBG SUBSCRIBE << mqttx_5f9b7c1c hook=debug m={"filters":{"$share/g1/a/b/c1":0},"subids":{"$share/g1/a/b/c1":0}}
4:54PM DBG SUBACK >> mqttx_5f9b7c1c hook=debug m={"reasons":[0]}
4:54PM DBG CONNECT <<  hook=debug m={"clean":true,"id":"mqtt_cli_342929000","keepalive":30,"username":"iotx","version":4}
4:54PM DBG CONNACK >> mqtt_cli_342929000 hook=debug m={"id":0,"reason":0}
4:54PM DBG PUBLISH << mqtt_cli_342929000 hook=debug m={"id":0,"payload":"test","qos":0,"raw":"dGVzdA==","topic":"a/b/c1"}
4:54PM DBG PUBLISH >> mqttx_5f9b7c1c hook=debug m={"id":0,"payload":"test","qos":0,"raw":"dGVzdA==","topic":"a/b/c1"}
4:54PM DBG DISCONNECT << mqtt_cli_342929000 hook=debug m={"id":0,"reason":0}
4:54PM DBG client disconnected client=mqtt_cli_342929000 listener=t1 remote=127.0.0.1:50365
4:54PM DBG UNSUBSCRIBE << mqttx_5f9b7c1c hook=debug m={"filters":["$share/g1/a/b/c1"]}
4:54PM DBG UNSUBACK >> mqttx_5f9b7c1c hook=debug m={"reasons":[17]}
4:54PM DBG SUBSCRIBE << mqttx_5f9b7c1c hook=debug m={"filters":{"$share/g1/a/b/c2":0},"subids":{"$share/g1/a/b/c2":0}}
4:54PM DBG SUBACK >> mqttx_5f9b7c1c hook=debug m={"reasons":[0]}
4:54PM DBG CONNECT <<  hook=debug m={"clean":true,"id":"mqtt_cli_224505000","keepalive":30,"username":"iotx","version":4}
4:54PM DBG CONNACK >> mqtt_cli_224505000 hook=debug m={"id":0,"reason":0}
4:54PM DBG PUBLISH << mqtt_cli_224505000 hook=debug m={"id":0,"payload":"test","qos":0,"raw":"dGVzdA==","topic":"a/b/c1"}
4:54PM DBG PUBLISH >> mqttx_5f9b7c1c hook=debug m={"id":0,"payload":"test","qos":0,"raw":"dGVzdA==","topic":"a/b/c1"}
4:54PM DBG DISCONNECT << mqtt_cli_224505000 hook=debug m={"id":0,"reason":0}
4:54PM DBG client disconnected client=mqtt_cli_224505000 listener=t1 remote=127.0.0.1:50381
4:55PM DBG CONNECT <<  hook=debug m={"clean":true,"id":"mqtt_cli_204904000","keepalive":30,"username":"iotx","version":4}
4:55PM DBG CONNACK >> mqtt_cli_204904000 hook=debug m={"id":0,"reason":0}
4:55PM DBG PUBLISH << mqtt_cli_204904000 hook=debug m={"id":0,"payload":"test","qos":0,"raw":"dGVzdA==","topic":"a/b/c2"}
4:55PM DBG PUBLISH >> mqttx_5f9b7c1c hook=debug m={"id":0,"payload":"test","qos":0,"raw":"dGVzdA==","topic":"a/b/c2"}
4:55PM DBG DISCONNECT << mqtt_cli_204904000 hook=debug m={"id":0,"reason":0}
4:55PM DBG client disconnected client=mqtt_cli_204904000 listener=t1 remote=127.0.0.1:50418

**Comment by thedevop** [comment] 2023-06-15 17:50
That's a separate issue, the RC of the new issue is module hardcodes $SHARE when checking for shared subscription. I will provide a fix for that later today.

**Comment by thedevop** [comment] 2023-06-15 18:00
@x20080406 , the behavior you see above is another issue. The RC is the module was doing a case-sensitive comparison for `$SHARE`. i'll provide a fix later today.

**Comment by thedevop** [comment] 2023-06-15 19:44
@x20080406 , take a look at the latest PR #243. Let me know if this fixed the issue.

**Comment by mochi-co** [comment] 2023-06-19 09:31
This should now be fixed in https://github.com/mochi-co/mqtt/releases/tag/v2.2.14 - please let me know 👍🏻 Thanks again for your help, @thedevop @x20080406 !

**Closed** 2023-06-19 19:54 UTC
